# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - id: Log build parameters 
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash' 
    args:
      - -c
      - |
          echo Build Settings:
          echo -------------------------------------------
          echo _CONTAINER_REGISTRY_PREFIX=$_CONTAINER_REGISTRY_PREFIX


  - id: Clone Saxml repo 
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash' 
    args:
      - -c
      - |
          git clone https://github.com/google/saxml

  - id: Buld Saxml dev container 
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash' 
    dir: saxml/saxml/tools/docker
    args:
      - -c
      - |
          sax_root_path=$(git rev-parse --show-toplevel)
          docker build -f Dockerfile.dev ${sax_root_path} -t sax-dev

  - id: Buld Saxml admin container 
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash' 
    dir: saxml/saxml/tools/docker
    args:
      - -c
      - |
          docker build -f Dockerfile.admin . -t sax-admin

  - id: Buld Saxml model server container 
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash' 
    dir: saxml/saxml/tools/docker
    args:
      - -c
      - |
          docker build -f Dockerfile.model . -t sax-model

  - id: Buld Saxml util container 
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash' 
    dir: saxml/saxml/tools/docker
    args:
      - -c
      - |
          docker build -f Dockerfile.util . -t sax-util

  - id: Tag images 
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash' 
    args:
      - -c
      - |
          docker tag sax-dev $_CONTAINER_REGISTRY_PREFIX/sax-dev 
          docker tag sax-model $_CONTAINER_REGISTRY_PREFIX/sax-model 
          docker tag sax-admin $_CONTAINER_REGISTRY_PREFIX/sax-admin 
          docker tag sax-util $_CONTAINER_REGISTRY_PREFIX/sax-util 

images:
  - $_CONTAINER_REGISTRY_PREFIX/sax-dev
  - $_CONTAINER_REGISTRY_PREFIX/sax-admin
  - $_CONTAINER_REGISTRY_PREFIX/sax-model
  - $_CONTAINER_REGISTRY_PREFIX/sax-util 

options:
  dynamic_substitutions: true