# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: python-hello-world"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/

apiVersion: batch/v1
kind: Job 
metadata:
  name: load-generator
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      restartPolicy: Never
      serviceAccountName: saxml-sa
      containers:
      - name: convert-job
        image: load-generator  
        command: ["python3", "load-generator.py"]
        args:
        - --model_id=$(MODEL_ID) 
        - --tokenizer=$(TOKENIZER)
        - --tpu_type=$(TPU_TYPE)
        - --tpu_topology=$(TPU_TOPOLOGY)
        - --data=$(TEST_DATA)
        - --output=$(OUTPUT_LOCATION)
        - --test_id=$(TEST_ID_PREFIX)
        - --num_batches=$(NUM_BATCHES)
        - --batch_size=$(BATCH_SIZE)
        - --num_threads=$(NUM_THREADS)
        - --per_example_max_decode_steps=$(PER_EXAMPLE_DECODE_STEPS)
        volumeMounts:
        - name:  gcs-fuse-ephemeral-model-repository
          mountPath: /model_repository
        envFrom:
        - configMapRef:
            name: load-generator-parameters
        env:
        - name: HUGGINGFACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: hugging-face 
              key: token
        resources:
          requests:
            memory: 4G 
          limits:
            memory: 4G
      volumes:
        - name: gcs-fuse-ephemeral-model-repository
          csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: bucket-name 
              mountOptions: "implicit-dirs"      