# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: python-hello-world"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator 
  template:
    metadata:
      labels:
        app: load-generator 
    spec:
      hostNetwork: false
      serviceAccountName: sax-sa
      containers:
      - name: load-generator 
        image: load-generator 
        command: ["tail", "-f", "/dev/null"]
        envFrom:
          - configMapRef:
              name: saxml-parameters
#        ports:
#        - containerPort: 8080
#        env:
#        - name: PORT
#          value: "8080"
#        readinessProbe:
#          tcpSocket:
#            port: 8080
#          initialDelaySeconds: 5